name: React App CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  deloyment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0' # Specify your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: sudo npm run build
      id: build
      continue-on-error: true

    - name: List Build Folder Contents
      run: ls -la ./build

      env:
        CI: false # Disable treating warnings as errors

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Lightsail
      run: |
        scp -r -o StrictHostKeyChecking=no ./build/* ubuntu@65.1.9.112:/home/ubuntu/inventory-demo/demo-inventory-frontend/build