name: React App CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0' # Specify your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build
      id: build
      continue-on-error: true

    - name: List Build Folder Contents
      run: ls -la ./build

      env:
        CI: false # Disable treating warnings as errors

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Lightsail
      run: |
        # Ensure SSH connection works first (optional step for testing)
        ssh -o StrictHostKeyChecking=no ubuntu@3.110.178.94 "echo 'SSH connection works!'"

        # Copy build files to the Lightsail instance
        scp -r -o StrictHostKeyChecking=no ./build/* ubuntu@3.110.178.94:/home/ubuntu/demo-inventory-frontend

        # Optional: Restart your application on Lightsail (if you use PM2 or any other process manager)
        ssh -o StrictHostKeyChecking=no ubuntu@3.110.178.94 'cd /home/ubuntu/demo-inventory-frontend && pm2 restart all'
